name: plano-k8s-rancher
#dependsOn:
#  - name: suc-upgrade-rancher
helm:
  takeOwnership: true
targetCustomizations:
- name: local
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local
  yaml:
    plano:
    # Refere-se ao diretório overlay
    - plano-k8s
