dependsOn:
  - name: suc-upgrade
- name: local
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local
  yaml:
    plano:
    # Refere-se ao diretório overlay
    - plano-k8s
