name: suc-upgrade-rancher
helm:
  takeOwnership: true
targetCustomizations:
- name: local
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local
  yaml:
    suc:
    # Refere-se ao diretório overlay
    - suc-k8s

